linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - govet

linters-settings:
  goimports:
    local-prefixes: github.com/bastiandoetsch/mullvad-best-server

output:
  format: tab

run:
  deadline: 10m
